<script src="<?=base_url()?>assets/admin/js/core/jquery.3.2.1.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/core/popper.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/core/bootstrap.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/plugin/chartist/chartist.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/plugin/chartist/plugin/chartist-plugin-tooltip.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/plugin/jquery-mapael/jquery.mapael.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/plugin/jquery-mapael/maps/world_countries.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/plugin/chart-circle/circles.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/ready.min.js"></script>
<script src="<?=base_url()?>assets/admin/js/demo.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
